sudo: required
services:
  - docker

before_install:
  - docker build -t manujapanday/docker-react -f Dockerfile.dev .

script:
  - docker run manujapanday/docker-react npm run test -- -coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-100607625307"
  bucket_path: "docker-react"
  on:
    brnch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
